print("True: %s" %(True and True))
print("False: %s" %(False and True))
print("False: %s" % (1 == 1 and 2 == 1))
print("True: %s" % ("test" == "test"))
print("True: %s" % (1 == 1 or 2 != 1))
print("True: %s" % (True and 1 == 1))
print("False: %s" % (False and 0 != 0))
print("True: %s" % (True or 1 == 1))
print("False: %s" % ("test" == "testing"))
print("False: %s" % (1 != 0 and 2 == 1))
print("True: %s" % ("test" != "testing"))
print("False: %s" % ("test" == 1))
print("True: %s" % (not (True and False)))
print("False: %s" % (not (1 == 1 and 0 != 1)))
print("False: %s" % (not (10 == 1 or 1000 == 1000)))
print("False: %s" % (not (1 != 10 or 3 == 4)))
print("True: %s" % (not ("testing" == "testing" and "Zed" == "Cool Guy")))
print("True: %s" % (1 == 1 and not ("testing" == 1 or 1 == 0)))
print("False: %s" % ("chunky" == "bacon" and not (3 == 4 or 3 == 3)))
print("False: %s" % (3 == 3 and not ("testing" == "testing" or "Python" == "Fun")))